# docker-compose.yml
version: '3'

services:
  app:
    build: ./app
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/appdb
    depends_on:
      - mongo

  mongo:
    build: ./mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
